version: '3.8'

services:
  db:
    image: postgres:13
    container_name: ml_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anupam
      POSTGRES_DB: ml_fastapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: ml_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:anupam@ml_db:5432/ml_fastapi
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port","8000", "--reload"]
    volumes:
      - ./app/models:/app/models


  redis:
    image: redis:latest
    container_name: ml_redis
    restart: always
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: ml_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ml_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ml_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ml_kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      
volumes:
  pgdata: