name = CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: make install

    - name: Lint with flake8
      run: make lint

    - name: Test with pytest
      run: make test

    - name: Build and push Docker image
      run: make docker-build